Accidentally mucked up the rust versions
Passed in an array instead of a single value. So travis tries to install
Rust and you get this:

$ curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
info: downloading installer
error: invalid toolchain name: '["nightly"]'